version: "3.7"

services:
  postgresql:
    build:
      context: postgresql/
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - postgresql-network

  pgadmin:
    build:
      context: pgadmin/
      dockerfile: Dockerfile
      args:
        PGADMIN_VERSION: ${PGADMIN_VERSION}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:
      - type: volume
        source: pgadmin-data
        target: /var/lib/pgadmin
    links:
      - "postgresql:pgsql-server"
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    depends_on:
      - postgresql
    networks:
      - postgresql-network

networks:
  postgresql-network:
    driver: bridge

volumes:
  postgresql-data:
  pgadmin-data: